#!/usr/bin/env python


def contains(i, s): return s(i)

def containsAll(elems, s):
    return reduce(lambda acc, element: s(element) and acc, elems, True)

def containsNo(elems, s):
    return reduce(lambda acc, element: not s(element) and acc, elems, True)

empty = lambda i: False

def singleton(i):
    return lambda b: i == b

def multiple(*elems):
    return lambda b: b in elems

def insert(i, s):
    return lambda b: i == b or s(b)

def remove(i, s):
    return lambda b: False if i == b else s(b)

def union(s1, s2):
    return lambda b: s1(b) or s2(b)

def intersection(s1, s2):
    return lambda b: s1(b) and s2(b)


assert(not contains(1, empty))

assert(contains(1, singleton(1)))

assert(
    (lambda s: contains(1, s) and not contains(2, s))
    (singleton(1)))

assert(contains(1, insert(1, empty)))

assert(
    (lambda s: contains(1, s) and not contains(2, s))
    (insert(1, empty)))

assert(not contains(1, remove(1, singleton(1))))

assert(
    (lambda s: contains(1, s) and not contains(2, s))
    (remove(2, insert(1, singleton(2)))))

assert(
    (lambda s: containsAll([1, 2, 3, 4], s))
    (union(multiple(1, 2), multiple(3, 4))))

assert(
    (lambda s: contains(2, s) and containsNo([1, 3], s))
    (intersection(multiple(1, 2), multiple(2, 3))))
